[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["Barlog <barlog@tanelorn.li>"]
edition = "2021"
rust-version = "1.57"

[dependencies]

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'
